// Norwegian (Dano-Norwegian) sentences sourced from Henrik Ibsen's plays,
// retrieved from Wikikilden (no.wikisource.org). Mix of original lines and
// near-paraphrases — used as placeholder ("lorem ipsum") material.
//
// Public domain — Ibsen died in 1906.
export const SENTENCES = [
  // Et dukkehjem (1879)
  "Gjem juletreet godt, Helene.",
  "Børnene må endelig ikke få se det før i aften.",
  "Nora lukker døren og ler stille fornøyet mens hun tar av yttertøyet.",
  "Det er jo den første jul vi ikke behøver å spare.",
  "Fra nyttår av får jeg en stor gasje.",
  "Ingen gjeld skal vi ha, aldri låne.",
  "Herregud, jeg vet jo nok at det går mye til i juletiden.",
  "Her er nye klær til Ivar og en sabel.",
  "Her er en hest og trompet til Bob.",
  "Her er dukke og dukkeseng til Emmy.",
  "Spillefuglen er søt, men den bruker svært mange penge.",
  "Jeg sparer dog virkelig alt hva jeg kan.",
  "Du er som din far var, alltid på jakt etter penge.",
  "De siste åtte år har vært en lykkelig tid for oss.",
  "Min mann er blitt direktør i Aksjebanken.",
  "Vi har måttet arbeide begge to for å få det vi har.",
  "Han ble så dødelig syk av overanstrengelse.",
  "Lægene sa at han måtte reise til syden.",
  "Reisen kostet tolv hundre spesier, fire tusen åtte hundre kroner.",
  "Pappa ga oss pengene til reisen.",
  "Jeg kunne ikke reise til ham da han lå syk.",
  "Det er meg som har reddet Torvalds liv.",
  "Jeg skaffet pengene til veien.",
  "En kone kan ikke låne uten sin manns samtykke.",
  "Jeg hadde en smule forretningsdyktighet.",
  "Han måtte ikke vite hvor farlig det sto til med ham.",
  "Jeg talte til ham om å reise til utlandet.",
  "Torvald er så streng i slike stykker.",
  "Det ville forrykke forholdet mellom oss.",
  "Jeg har måttet spare litt hist og her hvor jeg kunne.",
  "Av husholdningspengene kunne jeg ikke legge noe til side.",
  "Noras yttertøy ligger på sofaen.",
  "Han har tæring i ryggmarven.",
  "Torvald holder jo så ubeskrivelig meget av meg.",
  "Doktor Rank kommer hver evige dag her i huset.",
  "Jeg må ut av det annet som er bak hans rygg.",
  "Helmer har vært nede i banken.",
  "Krogstad har fått sin oppsigelse fra banken.",
  "Der ligger et brev i brevkassen fra Krogstad.",
  "Fru Linde er kommet til værelset fra venstre.",
  "Doktor Rank sitter ved ovnen og taler med Nora.",
  "Nora danser tarantellaen med stigende villhet.",
  "Helmer spiller piano mens Nora danser.",
  "Stuepiken bringer lampen inn i stuen.",
  "Nora teller timene som gjenstår før midnatt.",
  "Vi to skibbrudne mennesker kunne komme over til hinannen.",
  "Jeg må arbeide hvis jeg skal bære livet.",
  "Jeg trenger til noen å være mor for.",
  "Helmer må få vite alt sammen.",
  "Det må komme til full forklaring imellem de to.",
  "Mennesker å arbeide for, å leve for, et hjem å bringe hygge inn i.",
  "Nora er kledd i det italienske kostyme med et stort sort sjal over seg.",
  "Hovedsaken er at hun gjør lykke; hun gjør stormende lykke.",
  "En avslutning bør alltid være virkningsfull.",
  "Doktor Rank har stukket inn sine kort; han vil lukke seg inne og dø.",
  "Han var så sammenvokset med oss.",
  "Nu er vi to ganske henvist til hinannen alene.",
  "Jeg ønsker at en overhengende fare måtte true deg.",
  "Vi er frelst, Nora, både du og jeg.",
  "Nora har kjempet en hård strid i tre dager.",
  "Et stivnet uttrykk ligger over Noras ansikt.",
  "Børnene får du ikke lov til å oppdra.",
  "Nora må stå ganske alene for å få rede på seg selv.",
  "Hun vil gå fra huset straks og ta bare det som er hennes egen eiendom.",
  "Jeg vet bare at jeg blir nødvendig for meg selv.",
  "Folk vil si hva de vil si.",
  "Pliktene imot seg selv er like hellige som pliktene imot familie.",
  "Først og fremst er jeg et menneske.",
  "Hun har levet som et fattig menneske bare fra hånden til munnen.",
  "Vårt hjem har ikke vært annet enn en lekestue.",
  "Lekens tid skal være forbi.",
  "Hun kommer tilbake med sitt yttertøy og en liten vadsekk.",
  "Hun løser Helmer fra alle forpliktelser og gir ham tilbake sin brudering.",
  "Nora går ut gjennom forstuen, og drønnet av en port som slås i lås høres nedenfra.",

  // Peer Gynt (1867)
  "Alt ihob er tøv og tant.",
  "Det er sandt, hvert evigt ord.",
  "Først så render du tilfjelds månedsvis i travle annen.",
  "Kommer hjem med reven pels, uden byrse, uden vildt.",
  "Vest ved Gjendin traff jeg bukken.",
  "Hvasse vinden bar ifra og han grov efter lav.",
  "Pusten holdt jeg, stod og lytted efter knirken af hans hov.",
  "Slig en bukk, så blank og fed, skulde du vel aldri set.",
  "Bukken stupte bums i bakken og jeg sad skrævs på bukkeryggen.",
  "Gjendin-eggen er halve milen lang, hvass bortefter, som en ljå.",
  "Aldri red jeg slig en fole i mitt liv.",
  "Brune ørnerygge svam i det vide svimle slug.",
  "Isflak brast og brød mod strandene uden døn at høre.",
  "Bukk fra luften og bukk fra bunden stangedes i samme stund.",
  "Jeg for hjem og bukken går der vel ennå.",
  "Buksen har dog fått en revne, men det er knapt ved at nevne.",
  "Remsen, som du kommer med, minds jeg at jeg har kjennt før.",
  "En løgn kan endevendes og klædes i en nygjordt ham.",
  "Jeg skal blive konge, keiser når jeg får tid.",
  "Hægstadjenten var dig god, og du havde vundet spillet.",
  "Mads Moen fæstet jenten mens jeg red på bukke.",
  "Bryllupet skal stå imorgen på Hægstad.",
  "Der ligger Hægstad og snart er jeg fremme.",
  "Sendingsfolk myldrer tilgårde som myg.",
  "Den som havde noget stærkt at drikke var bedst for mig.",
  "Faer hans var fordrukken, og moer hans er låk.",
  "Jeg rider først og der følger mig mange i sporet.",
  "Keiser Peer Gynt og hans tusinde svende rider over havet.",
  "Engellands stormænd reiser sig når Peer rider frem.",
  "Jeg har manet fanden ind i en nød en gang.",
  "Den var ormstukken og jeg dytted hullet med en pind.",
  "Fanden hyttede sig som en brand tvers gjennem taget.",
  "Jeg kan ride rakt gjennem luften på gilde heste.",
  "Hele sognet skal mig tilfode falle når jeg rider.",
  "Vær deg selv – nok.",
  "Gå udenom, sa Bøjgen.",

  // Atmospheric Ibsen-stage-direction style fillers (composed in his idiom)
  "Aftensol falder ind gjennem vinduerne på den nordre væg.",
  "Et net og hyggeligt møbleret værelse, dog ikke med pragt.",
  "Det banker tre korte slag på døren i forstuen.",
  "Lampen brænder lavt på bordet ved sofaen.",
  "Stuen ligger i halvskumring, og kun et glødende kul lyser fra ovnen.",
  "Sneen driver imod vinduerne fra havet og fra fjorden.",
  "En slæde høres glide forbi udenfor med klingende bjælder.",
  "Det er sent på aftenen, og lyset fra gaden trænger ind mellem gardinerne.",
  "Vinden suser ned fra fjeldet og gnir mod husets vægger.",
  "Hun ser stivt fremfor sig og lægger hænderne i fanget.",
  "Han træder et skridt nærmere og ser hende roligt ind i øjnene.",
  "Hun går langsomt hen til vinduet og stirrer ud i mørket.",
  "Han lægger hatten fra sig på bordet og tager sig en stol.",
  "Et fjernt klokkespil lyder fra kirken nede ved torvet.",
  "Hun rejser sig brat og slipper bogen ned på gulvet.",
  "Han bliver stående med ryggen til ovnen og betragter hende.",
  "Stuen er nu helt mørk, kun en svag stripe lys falder under døren.",
  "Den unge mand ler kort, men lyden bliver hængende i rummet.",
  "Hun rækker hånden frem som om hun vilde tale, men trækker den til seg igen.",
  "Et brev ligger uåbnet på det lille bord ved sofaen.",
  "Han har glemt sine handsker på stolen ved døren.",
  "Hun knytter sjalet tettere om skuldrene og vender sig bort.",
];

// Tokens drawn from the corpus, for word-mode generation.
export const WORDS = SENTENCES
  .join(" ")
  .replace(/[.,;:?!()«»–—]/g, " ")
  .split(/\s+/)
  .filter(w => w.length > 0)
  .map(w => w.toLowerCase());
